[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "attendify"
version = "0.1.0"
description = "Attendance management system"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["app"] 