"""Update password_reset_tokens schema

Revision ID: ff6eaf77465d
Revises: update_password_hash_field
Create Date: 2025-05-25 16:36:53.713695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff6eaf77465d'
down_revision: Union[str, None] = 'update_password_hash_field'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_logs_user_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('idx_class_users_class_id'), table_name='class_users')
    op.drop_index(op.f('idx_class_users_group_id'), table_name='class_users')
    op.drop_index(op.f('idx_class_users_user_id'), table_name='class_users')
    op.drop_table('class_users')
    op.drop_table('group_users')
    op.drop_table('user_verifications')
    op.drop_index(op.f('idx_sessions_class_id'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_created_by'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_password_reset_tokens_token_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('email'), table_name='pre_verifications')
    op.drop_index(op.f('fk_pre_verifications_user'), table_name='pre_verifications')
    op.drop_table('pre_verifications')
    op.drop_index(op.f('idx_attendance_session_id'), table_name='attendance')
    op.drop_index(op.f('idx_attendance_user_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('class_code'), table_name='classes')
    op.drop_index(op.f('idx_classes_created_by'), table_name='classes')
    op.drop_index(op.f('ix_classes_class_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('group_code'), table_name='groups')
    op.drop_index(op.f('idx_group_code'), table_name='groups')
    op.drop_index(op.f('idx_groups_class_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False, comment="Adresse email unique de l'utilisateur"),
    sa.Column('password_hash', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('face_id_hash', mysql.TEXT(), nullable=True, comment='Hachage des données biométriques du visage'),
    sa.Column('face_id_vector', mysql.TEXT(), nullable=True, comment="Vecteur d'encodage des caractéristiques du visage"),
    sa.Column('face_id_encrypted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Indique si les données biométriques sont chiffrées'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='Date et heure de création du compte'),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True, comment='Date et heure de la dernière mise à jour'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Indique si le compte est actif'),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment="Indique si l'utilisateur est un administrateur"),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('prenom', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('groups',
    sa.Column('group_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('group_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('max_members', mysql.INTEGER(), server_default=sa.text("'5'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], name='fk_group_class', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='fk_group_creator'),
    sa.PrimaryKeyConstraint('group_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_groups_class_id'), 'groups', ['class_id'], unique=False)
    op.create_index(op.f('idx_group_code'), 'groups', ['group_code'], unique=False)
    op.create_index(op.f('group_code'), 'groups', ['group_code'], unique=True)
    op.create_table('classes',
    sa.Column('class_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('class_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='classes_ibfk_1'),
    sa.PrimaryKeyConstraint('class_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_classes_class_id'), 'classes', ['class_id'], unique=False)
    op.create_index(op.f('idx_classes_created_by'), 'classes', ['created_by'], unique=False)
    op.create_index(op.f('class_code'), 'classes', ['class_code'], unique=True)
    op.create_table('attendance',
    sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('marked_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', mysql.ENUM('present', 'absent'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name=op.f('attendance_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('attendance_ibfk_2')),
    sa.PrimaryKeyConstraint('session_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_attendance_user_id'), 'attendance', ['user_id'], unique=False)
    op.create_index(op.f('idx_attendance_session_id'), 'attendance', ['session_id'], unique=False)
    op.create_table('pre_verifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('verification_code', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('prenom', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('pre_verifications_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('fk_pre_verifications_user'), 'pre_verifications', ['user_id'], unique=False)
    op.create_index(op.f('email'), 'pre_verifications', ['email'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('token_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('password_reset_tokens_ibfk_1'), ondelete='CASCADE'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_token_id'), 'password_reset_tokens', ['token_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_topic', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('session_date', sa.DATE(), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=True),
    sa.Column('end_time', mysql.TIME(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qr_code', mysql.TEXT(), nullable=True),
    sa.Column('qr_last_updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], name=op.f('sessions_ibfk_1')),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('sessions_ibfk_2')),
    sa.PrimaryKeyConstraint('session_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_sessions_created_by'), 'sessions', ['created_by'], unique=False)
    op.create_index(op.f('idx_sessions_class_id'), 'sessions', ['class_id'], unique=False)
    op.create_table('user_verifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verification_code', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_verifications_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_verifications_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('group_users',
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], name=op.f('group_users_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('group_users_ibfk_2')),
    sa.PrimaryKeyConstraint('group_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('class_users',
    sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joined_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', mysql.VARCHAR(length=20), server_default=sa.text("'member'"), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], name=op.f('class_users_ibfk_1')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], name=op.f('fk_class_user_group'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('class_users_ibfk_2')),
    sa.PrimaryKeyConstraint('class_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_class_users_user_id'), 'class_users', ['user_id'], unique=False)
    op.create_index(op.f('idx_class_users_group_id'), 'class_users', ['group_id'], unique=False)
    op.create_index(op.f('idx_class_users_class_id'), 'class_users', ['class_id'], unique=False)
    op.create_table('logs',
    sa.Column('log_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('logs_ibfk_1')),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_logs_user_id'), 'logs', ['user_id'], unique=False)
    # ### end Alembic commands ###
